### ISSUE TITLE
Cannot signup to API manager 

### ISSUE THREAD

**Issue by nalakas** [wso2/carbon-apimgt#5600] opened 2018-08-20 08:25 UTC
**Description:**
unable to signup to API manager. the error given is 500.
[ApiSignupissue.txt](https://github.com/wso2/carbon-apimgt/files/2301684/ApiSignupissue.txt)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2am-2.6.0-alpha2-SNAPSHOT

**OS, DB, other environments details and versions:**    
OS:mac os high sierra
DB: h2 database

**Steps to reproduce:**
1.published api as a admin. 
2.try to sign as a admin.
3.try to signup

**Related Issues:**

**Comment by praminda** [comment] 2018-08-20 08:28
@nalakas  
Please fill in following sections.

**Affected Product Version:
OS, DB, other environments details and versions:
Steps to reproduce:**

**Comment by praminda** [comment] 2018-08-20 10:11
Duplicate of wso2/product-apim#3623

**Closed** 2018-08-20 10:10 UTC
Labels: APIM 2.6.0, Priority/Highest, Severity/Blocker
