### ISSUE TITLE
[OB] Failure in devportal key generation

### ISSUE THREAD

**Issue by Dinushi** [wso2/carbon-apimgt#9908] opened 2021-02-24 06:13 UTC
### Description:

An error occurs when generating production keys for a application created in devportal in the OB solution which is based on the API manger 3.1 version.

### Affected Product Version: 
OB-AM 2.0.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by chashikajw** [comment] 2021-02-24 11:14
Closing this issue since the issue is fixed.

**Closed by chashikajw** 2021-02-24 11:14 UTC
Labels: Priority/Normal, Type/Bug
